export const socketService = {
  connect: jest.fn(),
  disconnect: jest.fn(),
  removeAllListeners: jest.fn(),
  onItemCreated: jest.fn(),
  onItemUpdated: jest.fn(),
  onItemDeleted: jest.fn(),
  onTodoCreated: jest.fn(),
  onTodoUpdated: jest.fn(),
  onTodoDeleted: jest.fn(),
  onCategoryCreated: jest.fn(),
  onCategoryUpdated: jest.fn(),
  onCategoryDeleted: jest.fn(),
  onLocationCreated: jest.fn(),
  onLocationUpdated: jest.fn(),
  onLocationDeleted: jest.fn(),
  onReminderFired: jest.fn(),
  onMessageCreated: jest.fn(),
  onConversationUpdated: jest.fn(),
  onFriendRequestUpdated: jest.fn(),
};
